### PR TITLE
created sub-sub header for dashboard page

### PR DESCRIPTION
**Pull request by alena-andr**

### CODE REVIEW

**Comment by Gerasimov94** [comment]
sub-sub))

**Comment by CodeAnnihilator** [comment]
image

**Comment by CodeAnnihilator** [comment]
image
this is how we should show our navigation for public routes, not private

**Comment by CodeAnnihilator** [comment]
for private routes, header should not have routes like home/pricing/blog/sign in/sign up. There should only be logo sticked to the left side, and user and lang sticked to the right

**Comment by CodeAnnihilator** [comment]
image
this nav control element should only be visible on protected routes

**Comment by CodeAnnihilator** [comment]
image
should be called 'цены'

**Comment by CodeAnnihilator** [comment]
image
this is approximately how our logo part should look like

**Comment by CodeAnnihilator** [comment]
image
this is how our button should look like

**Comment by CodeAnnihilator** [comment]
image
searchbar should take all available space in a row

**Comment by CodeAnnihilator** [comment]
image
this is how our right side of a header on protected routes should look like

**Comment by CodeAnnihilator** [comment]
image
if user is authenticated, on a public routes we should not be able to see sign in/sign up, only

**Comment by CodeAnnihilator** [comment]
use random avatar from http://i.pravatar.cc/200

**Comment by CodeAnnihilator** [comment]
fix header bg color to be more green-ish in depth as we have in our design

**Review by CodeAnnihilator — APPROVED** [review]

**Pull request merged**
